USE [master]
GO

/****** Object:  Database [Journal_DEV]    Script Date: 5/5/2020 5:20:45 AM ******/
CREATE DATABASE [Journal_DEV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Journal_DEV', FILENAME = N'/var/opt/mssql/data/Journal_DEV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Journal_DEV_log', FILENAME = N'/var/opt/mssql/data/Journal_DEV_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Journal_DEV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Journal_DEV] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Journal_DEV] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Journal_DEV] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Journal_DEV] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Journal_DEV] SET ARITHABORT OFF 
GO

ALTER DATABASE [Journal_DEV] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Journal_DEV] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Journal_DEV] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Journal_DEV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Journal_DEV] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Journal_DEV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Journal_DEV] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Journal_DEV] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Journal_DEV] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Journal_DEV] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Journal_DEV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Journal_DEV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Journal_DEV] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Journal_DEV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Journal_DEV] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Journal_DEV] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Journal_DEV] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Journal_DEV] SET RECOVERY FULL 
GO

ALTER DATABASE [Journal_DEV] SET  MULTI_USER 
GO

ALTER DATABASE [Journal_DEV] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Journal_DEV] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Journal_DEV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Journal_DEV] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Journal_DEV] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Journal_DEV] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Journal_DEV] SET  READ_WRITE 
GO


